language: node_js
node_js:
- '4'
branches:
  only:
  - sources
env:
  global:
      REPO:
          github.com:happyhaha1/happyhaha1.github.io.git
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "happyhaha1"
- git config --global user.email "happyzhengkaixin@gmail.com" 
- sed -i'' "s~git@${REPO}~https://${GH_TOKEN}:x-oauth-basic@${REPO}~" _config.yml
k
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
